default_language_version:
    python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-ast
        name: python check ast
    -   id: trailing-whitespace
        name: trim trailing whitespace
        files: (.*\.py$|.*\.css$|.*\.js$|.*\.html$)
        exclude: (^.*\/migrations\/.*\.py$|.*\/node_modules\/.*|.*\/env\/.*)
    -   id: end-of-file-fixer
        name: end of line fixer
        files: (.*\.py$|.*\.css$|.*\.js$|.*\.html$)
        exclude: (^.*\/migrations\/.*\.py$|.*\/node_modules\/.*|.*\/env\/.*|.*\.min\.js$|.*\.min\.css$)
    -   id: check-merge-conflict
        name: check merge conflicts
-   repo: https://github.com/python/black
    rev: "22.3.0"
    hooks:
    -   id: black
        files: (?x)^.*\/.*\.pyi?$
        exclude: (?x)^(.*\/migrations\/.*\.py)$
        language: python
