
name: checkout & tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: check python version
        run: python --version
      - name: install requirements
        run: pip install -r requirements.txt
      - name: check pre-commit
        run: pre-commit run --all-files
      - name: run coverage & pytest
        run: coverage run -m pytest && coverage report -m
